// G2FEAT-134 — bolt's self-contained Zstandard decoder, verified byte-exact
// against python-zstandard / pyarrow.
//
// WHY THIS EXISTS: zstd is pyiceberg's DEFAULT parquet codec, and bolt's
// parquet reader previously rejected it outright (PqCodec::Zstd fell into the
// `return false` arm), so the most common real Iceberg table on earth did not
// read. libzstd is optional and is not linked on a default build -- and is not
// installed on the dev box at all -- so the codec is owned, exactly as
// bolt_inflate.cpp owns DEFLATE rather than depending on zlib.
//
// THREE LAYERS OF VERIFICATION:
//   1. ZstdVectors     -- 33 reference frames from python-zstandard, decoded
//                         and compared BYTE FOR BYTE. Covers every block type
//                         (Raw/RLE/Compressed), every literal mode (Raw/RLE/
//                         Huffman 1- and 4-stream/Treeless) and every sequence
//                         mode (Predefined/RLE/FSE_Compressed/Repeat) that a
//                         real writer emits -- measured, not assumed. Six of
//                         the vectors are REAL parquet pages.
//   2. ZstdParquet     -- golden_zstd.parquet, a real pyarrow zstd file, read
//                         end to end through bolt's parquet reader with every
//                         value asserted. THIS TEST FAILS ON THE PRE-G2FEAT-134
//                         CODE BY CONSTRUCTION (the reader returned false).
//   3. ZstdMalformed   -- truncations, bit flips and random bytes must return
//                         an error code, never crash, never read/write out of
//                         bounds. (A dedicated ASAN mutation run covering ~93k
//                         malformed inputs was done during development; this
//                         keeps a bounded regression subset in CI.)
//
// Fixtures are regenerated by tests/data/make_zstd_vectors.py, which documents
// the deterministic patterns this file re-derives in `materialize()`.

#include "bolt/ingest/bolt_zstd_dec.h"

#include <gtest/gtest.h>

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include "bolt/bolt_arena.h"
#include "bolt/bolt_column.h"
#include "bolt/ingest/bolt_parquet_read.h"

namespace {

using namespace bolt::ingest;

std::vector<uint8_t> slurp(const std::string& path) {
    std::vector<uint8_t> v;
    std::FILE* f = std::fopen(path.c_str(), "rb");
    if (f == nullptr) return v;
    std::fseek(f, 0, SEEK_END);
    const long n = std::ftell(f);
    std::fseek(f, 0, SEEK_SET);
    v.resize(static_cast<size_t>(n));
    const size_t got = std::fread(v.data(), 1, v.size(), f);
    std::fclose(f);
    if (got != v.size()) v.clear();
    return v;
}

std::string data_path(const char* name) {
    return std::string(BOLT_TEST_DATA_DIR) + "/" + name;
}

// --- the deterministic patterns, mirroring make_zstd_vectors.py -------------
enum : uint32_t {
    kInline = 0, kZeros = 1, kConst = 2, kRepeat = 3,
    kLcg = 4, kAlpha = 5, kChunks = 6,
};
constexpr uint64_t kMul = 6364136223846793005ull;
constexpr uint64_t kInc = 1442695040888963407ull;

void lcg_fill(uint8_t* dst, uint64_t n, uint64_t seed) {
    uint64_t s = seed;
    for (uint64_t i = 0; i < n; ++i) {
        s = s * kMul + kInc;
        dst[i] = static_cast<uint8_t>((s >> 33) & 0xFFu);
    }
}

struct Vector {
    std::string          name;
    uint32_t             kind = 0;
    uint64_t             raw_len = 0;
    uint64_t             seed = 0;
    uint32_t             aux = 0;
    std::vector<uint8_t> pat;
    std::vector<uint8_t> inl;
    std::vector<uint8_t> comp;
};

std::vector<uint8_t> materialize(const Vector& v) {
    std::vector<uint8_t> r;
    switch (v.kind) {
        case kInline: return v.inl;
        case kZeros:  r.assign(static_cast<size_t>(v.raw_len), 0); return r;
        case kConst:
            r.assign(static_cast<size_t>(v.raw_len),
                     static_cast<uint8_t>(v.seed & 0xFFu));
            return r;
        case kRepeat: {
            r.resize(static_cast<size_t>(v.raw_len));
            if (v.pat.empty()) return r;
            for (size_t i = 0; i < r.size(); ++i) r[i] = v.pat[i % v.pat.size()];
            return r;
        }
        case kLcg:
            r.resize(static_cast<size_t>(v.raw_len));
            if (!r.empty()) lcg_fill(r.data(), r.size(), v.seed);
            return r;
        case kAlpha: {
            r.resize(static_cast<size_t>(v.raw_len));
            uint64_t s = v.seed;
            for (size_t i = 0; i < r.size(); ++i) {
                s = s * kMul + kInc;
                r[i] = static_cast<uint8_t>('a' + ((s >> 33) % v.aux));
            }
            return r;
        }
        case kChunks: {
            uint32_t clen = 0, reps = 0;
            std::memcpy(&clen, v.pat.data(), 4);
            std::memcpy(&reps, v.pat.data() + 4, 4);
            const uint8_t lit = v.pat[8];
            const uint32_t k = v.aux;
            std::vector<std::vector<uint8_t>> chunks(k);
            for (uint32_t i = 0; i < k; ++i) {
                chunks[i].resize(clen);
                lcg_fill(chunks[i].data(), clen, v.seed + 1u + i);
            }
            r.reserve(static_cast<size_t>(k) * clen +
                      static_cast<size_t>(reps) * (clen + 1u));
            for (uint32_t i = 0; i < k; ++i)
                r.insert(r.end(), chunks[i].begin(), chunks[i].end());
            uint64_t s = v.seed;
            for (uint32_t i = 0; i < reps; ++i) {
                s = s * kMul + kInc;
                r.push_back(lit);
                const auto& c = chunks[(s >> 33) % k];
                r.insert(r.end(), c.begin(), c.end());
            }
            return r;
        }
        default: return r;
    }
}

std::vector<Vector> load_vectors() {
    std::vector<Vector> out;
    std::vector<uint8_t> b = slurp(data_path("zstd_vectors.bin"));
    if (b.size() < 4) return out;
    size_t o = 0;
    auto need = [&](size_t k) { return o + k <= b.size(); };
    auto r32 = [&]() { uint32_t v; std::memcpy(&v, b.data() + o, 4); o += 4; return v; };
    auto r64 = [&]() { uint64_t v; std::memcpy(&v, b.data() + o, 8); o += 8; return v; };
    const uint32_t n = r32();
    for (uint32_t i = 0; i < n && need(4); ++i) {
        Vector v;
        const uint32_t nl = r32();
        if (!need(nl)) break;
        v.name.assign(reinterpret_cast<const char*>(b.data() + o), nl); o += nl;
        v.kind = r32();
        v.raw_len = r64();
        v.seed = r64();
        v.aux = r32();
        const uint32_t pl = r32();
        if (!need(pl)) break;
        v.pat.assign(b.begin() + o, b.begin() + o + pl); o += pl;
        const uint64_t il = r64();
        if (!need(static_cast<size_t>(il))) break;
        v.inl.assign(b.begin() + o, b.begin() + o + static_cast<size_t>(il));
        o += static_cast<size_t>(il);
        const uint64_t cl = r64();
        if (!need(static_cast<size_t>(cl))) break;
        v.comp.assign(b.begin() + o, b.begin() + o + static_cast<size_t>(cl));
        o += static_cast<size_t>(cl);
        out.push_back(std::move(v));
    }
    return out;
}

// Scratch is ~150 KB: heap, never a stack frame.
struct Scratch {
    std::vector<uint8_t> buf;
    void* ptr = nullptr;
    Scratch() {
        buf.resize(static_cast<size_t>(zstd_scratch_size()) + 64);
        ptr = reinterpret_cast<void*>(
            (reinterpret_cast<uintptr_t>(buf.data()) + 7u) & ~static_cast<uintptr_t>(7u));
    }
};

// ---------------------------------------------------------------------------
// 1. Byte-exact against python-zstandard
// ---------------------------------------------------------------------------
TEST(ZstdVectors, DecodeAllByteExact) {
    std::vector<Vector> vecs = load_vectors();
    ASSERT_GE(vecs.size(), 30u) << "zstd_vectors.bin missing or truncated; "
                                   "regenerate with make_zstd_vectors.py";
    Scratch sc;
    for (const Vector& v : vecs) {
        const std::vector<uint8_t> want = materialize(v);
        ASSERT_EQ(want.size(), v.raw_len) << v.name << ": pattern mismatch";
        std::vector<uint8_t> got(want.size() + 16, 0xCD);
        uint64_t n = 0;
        const int rc = zstd_decode_raw(v.comp.data(), v.comp.size(),
                                       got.data(), want.size(), &n,
                                       sc.ptr, zstd_scratch_size());
        ASSERT_EQ(rc, kZstdOk) << v.name;
        ASSERT_EQ(n, want.size()) << v.name;
        // byte-for-byte, reporting the first divergence
        for (uint64_t i = 0; i < want.size(); ++i) {
            if (got[static_cast<size_t>(i)] != want[static_cast<size_t>(i)]) {
                FAIL() << v.name << ": first byte difference at " << i
                       << " got=" << static_cast<int>(got[static_cast<size_t>(i)])
                       << " want=" << static_cast<int>(want[static_cast<size_t>(i)]);
            }
        }
    }
}

TEST(ZstdVectors, RejectsUndersizedOutputBuffer) {
    std::vector<Vector> vecs = load_vectors();
    ASSERT_FALSE(vecs.empty());
    Scratch sc;
    int short_cases = 0;
    for (const Vector& v : vecs) {
        if (v.raw_len < 2) continue;
        std::vector<uint8_t> got(static_cast<size_t>(v.raw_len));
        uint64_t n = 0;
        const int rc = zstd_decode_raw(v.comp.data(), v.comp.size(), got.data(),
                                       v.raw_len - 1, &n,
                                       sc.ptr, zstd_scratch_size());
        EXPECT_NE(rc, kZstdOk) << v.name << " decoded into a too-small buffer";
        ++short_cases;
    }
    EXPECT_GT(short_cases, 10);
}

TEST(ZstdVectors, RejectsTooSmallScratch) {
    std::vector<Vector> vecs = load_vectors();
    ASSERT_FALSE(vecs.empty());
    std::vector<uint8_t> small(64);
    std::vector<uint8_t> out(4096);
    uint64_t n = 0;
    EXPECT_EQ(zstd_decode_raw(vecs[0].comp.data(), vecs[0].comp.size(),
                              out.data(), out.size(), &n,
                              small.data(), small.size()),
              kZstdScratchSmall);
}

TEST(ZstdVectors, ContentChecksumIsVerified) {
    // "cksum" carries a frame content checksum. Corrupting a byte of the
    // payload must be CAUGHT, not silently returned as wrong data.
    std::vector<Vector> vecs = load_vectors();
    const Vector* cks = nullptr;
    for (const Vector& v : vecs) if (v.name == "cksum") cks = &v;
    ASSERT_NE(cks, nullptr);
    Scratch sc;
    std::vector<uint8_t> out(static_cast<size_t>(cks->raw_len) + 16);
    uint64_t n = 0;
    ASSERT_EQ(zstd_decode_raw(cks->comp.data(), cks->comp.size(), out.data(),
                              cks->raw_len, &n, sc.ptr, zstd_scratch_size()),
              kZstdOk);
    // flip a bit in the last literal byte region and expect a checksum error
    bool saw_checksum_error = false;
    for (size_t i = 8; i + 4 < cks->comp.size() && !saw_checksum_error; ++i) {
        std::vector<uint8_t> bad = cks->comp;
        bad[i] ^= 0x01u;
        uint64_t m = 0;
        const int rc = zstd_decode_raw(bad.data(), bad.size(), out.data(),
                                       out.size(), &m,
                                       sc.ptr, zstd_scratch_size());
        if (rc == kZstdChecksum) saw_checksum_error = true;
    }
    EXPECT_TRUE(saw_checksum_error)
        << "no single-bit corruption was caught by the content checksum";
}

TEST(ZstdVectors, RejectsDictionaryFramesLoudly) {
    // Frame_Header_Descriptor with Dictionary_ID_flag = 1. We deliberately do
    // not support dictionaries; the point is that it is REFUSED with a
    // specific code rather than mis-decoded.
    Scratch sc;
    const uint8_t frame[] = {
        0x28, 0xB5, 0x2F, 0xFD,   // magic
        0x21,                     // single_seg=1, did_flag=1
        0x07,                     // dictionary id
        0x00,                     // frame content size
    };
    std::vector<uint8_t> out(64);
    uint64_t n = 0;
    EXPECT_EQ(zstd_decode_raw(frame, sizeof(frame), out.data(), out.size(),
                              &n, sc.ptr, zstd_scratch_size()),
              kZstdUnsupported);
}

// ---------------------------------------------------------------------------
// 2. Real zstd parquet, end to end. FAILS ON PRE-G2FEAT-134 CODE.
// ---------------------------------------------------------------------------
TEST(ZstdParquet, GoldenZstdFileReadsWithExactValues) {
    using namespace bolt::ingest::parquet;
    std::vector<uint8_t> buf = slurp(data_path("golden_zstd.parquet"));
    ASSERT_FALSE(buf.empty()) << "golden_zstd.parquet missing";
    bolt::Arena arena;
    PqMeta* meta = static_cast<PqMeta*>(
        arena.allocate(sizeof(PqMeta), alignof(PqMeta)));
    ASSERT_NE(meta, nullptr);
    std::memset(meta, 0, sizeof(*meta));
    ASSERT_TRUE(parquet_read_meta(buf.data(), buf.size(), &arena, meta));
    ASSERT_EQ(meta->n_columns, 4u);
    ASSERT_EQ(meta->num_rows, 5000);
    ASSERT_GT(meta->n_row_groups, 1u);

    int64_t seen = 0;
    for (uint32_t g = 0; g < meta->n_row_groups; ++g) {
        bolt::BoltColumn cols[kPqMaxColumns];
        int64_t rows = 0;
        ASSERT_TRUE(parquet_read_row_group(buf.data(), buf.size(), meta, g,
                                           &arena, cols, &rows))
            << "row group " << g << " failed to decode -- this is exactly the "
               "pre-G2FEAT-134 behaviour (zstd pages were rejected)";
        ASSERT_GT(rows, 0);
        ASSERT_EQ(cols[0].type, bolt::BoltType::Int64);
        ASSERT_EQ(cols[1].type, bolt::BoltType::Int64);
        ASSERT_EQ(cols[2].type, bolt::BoltType::Float64);
        ASSERT_EQ(cols[3].type, bolt::BoltType::Utf8);
        const auto* id = static_cast<const int64_t*>(cols[0].data);
        const auto* v  = static_cast<const int64_t*>(cols[1].data);
        const auto* f  = static_cast<const double*>(cols[2].data);
        const auto* s  = static_cast<const bolt::StringView*>(cols[3].data);
        for (int64_t r = 0; r < rows; ++r) {
            const int64_t i = seen + r;
            EXPECT_EQ(id[r], i) << "row " << i;
            EXPECT_EQ(v[r], static_cast<int64_t>(
                          (static_cast<uint64_t>(i) * 2654435761ull) % 1000003ull))
                << "row " << i;
            EXPECT_DOUBLE_EQ(f[r], static_cast<double>(i) * 0.25) << "row " << i;
            char want[32];
            std::snprintf(want, sizeof(want), "row%05lld",
                          static_cast<long long>(i));
            const uint32_t wlen = static_cast<uint32_t>(std::strlen(want));
            ASSERT_EQ(s[r].length, wlen) << "row " << i;
            const char* got = (s[r].length <= 12u)
                ? &s[r].prefix[0]
                : static_cast<const char*>(cols[3].str_overflow_base) +
                      s[r].ref.offset;
            EXPECT_EQ(std::memcmp(got, want, wlen), 0) << "row " << i;
        }
        seen += rows;
    }
    EXPECT_EQ(seen, 5000);
}

TEST(ZstdParquet, ProjectionPushdownMatchesFullDecode) {
    using namespace bolt::ingest::parquet;
    std::vector<uint8_t> buf = slurp(data_path("golden_zstd.parquet"));
    ASSERT_FALSE(buf.empty());
    bolt::Arena arena;
    PqMeta* meta = static_cast<PqMeta*>(
        arena.allocate(sizeof(PqMeta), alignof(PqMeta)));
    ASSERT_NE(meta, nullptr);
    std::memset(meta, 0, sizeof(*meta));
    ASSERT_TRUE(parquet_read_meta(buf.data(), buf.size(), &arena, meta));
    for (uint32_t g = 0; g < meta->n_row_groups; ++g) {
        bolt::BoltColumn full[kPqMaxColumns];
        int64_t full_rows = 0;
        ASSERT_TRUE(parquet_read_row_group(buf.data(), buf.size(), meta, g,
                                           &arena, full, &full_rows));
        const uint16_t proj[2] = {2, 0};          // {f, id}, out of order
        bolt::BoltColumn cols[2];
        int64_t rows = 0;
        ASSERT_TRUE(parquet_read_row_group_cols(buf.data(), buf.size(), meta, g,
                                                proj, 2, &arena, cols, &rows));
        ASSERT_EQ(rows, full_rows);
        const auto* pf = static_cast<const double*>(cols[0].data);
        const auto* ff = static_cast<const double*>(full[2].data);
        const auto* pi = static_cast<const int64_t*>(cols[1].data);
        const auto* fi = static_cast<const int64_t*>(full[0].data);
        for (int64_t r = 0; r < rows; ++r) {
            EXPECT_DOUBLE_EQ(pf[r], ff[r]);
            EXPECT_EQ(pi[r], fi[r]);
        }
    }
}

// ---------------------------------------------------------------------------
// 3. Malformed input: error code, never a crash or an OOB access
// ---------------------------------------------------------------------------
TEST(ZstdMalformed, TruncationsAndFlipsNeverCrash) {
    std::vector<Vector> vecs = load_vectors();
    ASSERT_FALSE(vecs.empty());
    Scratch sc;
    uint64_t rng = 0x9E3779B97F4A7C15ull;
    auto next = [&]() {
        rng ^= rng << 13; rng ^= rng >> 7; rng ^= rng << 17; return rng;
    };
    long long ok = 0, err = 0;
    for (const Vector& v : vecs) {
        const size_t cap = static_cast<size_t>(v.raw_len) + 64;
        std::vector<uint8_t> out(cap);
        // truncations
        const size_t stride = v.comp.size() > 2048 ? v.comp.size() / 64 + 1 : 1;
        for (size_t len = 0; len < v.comp.size(); len += stride) {
            uint64_t n = 0;
            const int rc = zstd_decode_raw(v.comp.data(), len, out.data(),
                                           v.raw_len, &n,
                                           sc.ptr, zstd_scratch_size());
            (rc == kZstdOk) ? ++ok : ++err;
            if (rc == kZstdOk) EXPECT_LE(n, v.raw_len);
        }
        // bit flips
        for (int it = 0; it < 200; ++it) {
            if (v.comp.empty()) break;
            std::vector<uint8_t> bad = v.comp;
            const int nmut = 1 + static_cast<int>(next() % 3u);
            for (int m = 0; m < nmut; ++m) {
                bad[next() % bad.size()] ^= static_cast<uint8_t>(next() & 0xFFu);
            }
            uint64_t n = 0;
            const int rc = zstd_decode_raw(bad.data(), bad.size(), out.data(),
                                           v.raw_len, &n,
                                           sc.ptr, zstd_scratch_size());
            (rc == kZstdOk) ? ++ok : ++err;
            if (rc == kZstdOk) EXPECT_LE(n, v.raw_len);
        }
    }
    EXPECT_GT(err, 0);          // corruption must actually be detected
    SUCCEED() << ok << " decoded, " << err << " rejected; no crash";
}

TEST(ZstdMalformed, RandomBytesAreRejected) {
    Scratch sc;
    uint64_t rng = 0xDEADBEEFCAFEBABEull;
    auto next = [&]() {
        rng ^= rng << 13; rng ^= rng >> 7; rng ^= rng << 17; return rng;
    };
    std::vector<uint8_t> out(8192);
    for (int it = 0; it < 4000; ++it) {
        const size_t len = static_cast<size_t>(next() % 512u) + 1u;
        std::vector<uint8_t> c(len);
        for (size_t i = 0; i < len; ++i) c[i] = static_cast<uint8_t>(next() & 0xFFu);
        if ((next() & 1u) && len >= 4) {          // half carry a valid magic
            c[0] = 0x28; c[1] = 0xB5; c[2] = 0x2F; c[3] = 0xFD;
        }
        uint64_t n = 0;
        const int rc = zstd_decode_raw(c.data(), c.size(), out.data(),
                                       out.size(), &n,
                                       sc.ptr, zstd_scratch_size());
        if (rc == kZstdOk) EXPECT_LE(n, out.size());
    }
    SUCCEED();
}

TEST(ZstdMalformed, NullAndZeroLengthAreHandled) {
    Scratch sc;
    uint64_t n = 12345;
    std::vector<uint8_t> out(64);
    EXPECT_EQ(zstd_decode_raw(nullptr, 0, out.data(), out.size(), &n,
                              sc.ptr, zstd_scratch_size()), kZstdTruncSrc);
    EXPECT_EQ(n, 0u);
    const uint8_t one = 0x28;
    EXPECT_NE(zstd_decode_raw(&one, 1, out.data(), out.size(), &n,
                              sc.ptr, zstd_scratch_size()), kZstdOk);
}

}  // namespace
