// G2FEAT-23 (bolt half) — Parquet page index (ColumnIndex/OffsetIndex) +
// split-block bloom filter reader tests.
//
// Fixtures (tests/data/, generated by pyarrow 25 + duckdb 1.5.4 — see the
// tracker note; the real proj_100m/athena ClickBench artifacts carry
// NEITHER structure, so external-writer fixtures are the ground truth):
//
//   golden_pageindex.parquet   pyarrow, write_page_index=True, 2 rowgroups
//                              x 1000 rows, ~100-row pages (8-10/chunk).
//                              id      : int64 == global row index (sorted)
//                              val     : int32 == (row*7) % 1000
//                              name    : utf8  == "k%06d" % row  (sorted)
//                              opt     : int64 nullable, rows with
//                                        (row/100)%5 == 2 are null (pyarrow
//                                        merges the null span into a mixed
//                                        200-row page -> null_counts cover)
//                              allnull : int64, 100% null -> every page of
//                                        the chunk is a NULL PAGE
//   golden_bloom.parquet       pyarrow, SBBF blooms on id/name/val;
//                              id = 10000+3i, name = "user%05d" % i,
//                              val = 17i+5, i in [0,1000).
//   golden_bloom_duckdb.parquet duckdb (independent writer), blooms on
//                              id/name, same value scheme.
//
// Plus hostile-input fuzzing (truncations + byte flips over the index and
// bloom slices) and synthetic-buffer unit tests for the helpers.

#include "bolt/ingest/bolt_parquet_bloom.h"
#include "bolt/ingest/bolt_parquet_meta.h"
#include "bolt/ingest/bolt_parquet_pageindex.h"

#include <gtest/gtest.h>

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

namespace {

using namespace bolt::ingest::parquet;

std::vector<uint8_t> slurp(const char* path) {
    std::vector<uint8_t> v;
    std::FILE* f = std::fopen(path, "rb");
    if (f == nullptr) return v;
    std::fseek(f, 0, SEEK_END);
    const long n = std::ftell(f);
    std::fseek(f, 0, SEEK_SET);
    v.resize(static_cast<size_t>(n));
    const size_t got = std::fread(v.data(), 1, v.size(), f);
    std::fclose(f);
    if (got != v.size()) v.clear();
    return v;
}

std::string data_path(const char* name) {
    return std::string(BOLT_TEST_DATA_DIR) + "/" + name;
}

struct ParsedFile {
    std::vector<uint8_t> buf;
    std::vector<PqChunk> chunks;
    PqMeta meta{};
};

void parse_file(const char* name, ParsedFile* pf) {
    pf->buf = slurp(data_path(name).c_str());
    ASSERT_FALSE(pf->buf.empty()) << name;
    pf->chunks.resize(kPqMaxColumns * 64);
    std::memset(&pf->meta, 0, sizeof(pf->meta));
    pf->meta.chunks = pf->chunks.data();
    pf->meta.chunks_cap = static_cast<uint32_t>(pf->chunks.size());
    uint64_t off = 0;
    uint32_t len = 0;
    ASSERT_TRUE(pq_locate_footer(pf->buf.data(), pf->buf.size(), &off, &len));
    ASSERT_TRUE(pq_parse_file_meta(pf->buf.data() + off, len, &pf->meta));
}

const PqChunk& chunk_at(const ParsedFile& pf, uint32_t rg, uint32_t col) {
    return pf.meta.chunks[pf.meta.row_groups[rg].chunk_off + col];
}

// Parse both index halves of one chunk into caller storage.
struct ChunkIndex {
    std::vector<PqPageStat> stats{kPqMaxPagesPerChunk};
    std::vector<PqPageLocation> locs{kPqMaxPagesPerChunk};
    PqColumnIndex ci{};
    PqOffsetIndex oi{};
};

void read_chunk_index(const ParsedFile& pf, uint32_t rg, uint32_t col,
                      ChunkIndex* out) {
    const PqChunk& ch = chunk_at(pf, rg, col);
    out->ci.pages = out->stats.data();
    out->ci.pages_cap = static_cast<uint32_t>(out->stats.size());
    out->oi.pages = out->locs.data();
    out->oi.pages_cap = static_cast<uint32_t>(out->locs.size());
    ASSERT_TRUE(pq_read_column_index(pf.buf.data(), pf.buf.size(), ch,
                                     &out->ci));
    ASSERT_TRUE(pq_read_offset_index(pf.buf.data(), pf.buf.size(), ch,
                                     &out->oi));
    ASSERT_EQ(out->ci.n_pages, out->oi.n_pages);
    ASSERT_GE(out->ci.n_pages, 2u);   // fixture forces ~100-row pages
}

int64_t page_stat_i64(const PqPageStat& ps, bool want_min) {
    EXPECT_EQ(want_min ? ps.min_len : ps.max_len, 8u);
    int64_t v = 0;
    std::memcpy(&v, want_min ? ps.min_bytes : ps.max_bytes, 8);
    return v;
}

// ============================================================================
// Footer capture of the new PqChunk location fields
// ============================================================================

TEST(BoltParquetPageIndex, FooterCapturesIndexOffsets) {
    ParsedFile pf;
    parse_file("golden_pageindex.parquet", &pf);
    EXPECT_EQ(pf.meta.num_rows, 2000);
    ASSERT_EQ(pf.meta.n_columns, 5u);
    ASSERT_EQ(pf.meta.n_row_groups, 2u);
    for (uint32_t g = 0; g < pf.meta.n_row_groups; ++g) {
        for (uint32_t c = 0; c < pf.meta.n_columns; ++c) {
            const PqChunk& ch = chunk_at(pf, g, c);
            EXPECT_GT(ch.column_index_offset, 0) << g << "," << c;
            EXPECT_GT(ch.column_index_length, 0) << g << "," << c;
            EXPECT_GT(ch.offset_index_offset, 0) << g << "," << c;
            EXPECT_GT(ch.offset_index_length, 0) << g << "," << c;
            EXPECT_EQ(ch.bloom_filter_offset, 0) << g << "," << c;
        }
    }
    // Older fixture (no page index): all location fields stay absent.
    ParsedFile old;
    parse_file("golden_flat.parquet", &old);
    for (uint32_t i = 0; i < old.meta.n_chunks; ++i) {
        EXPECT_EQ(old.meta.chunks[i].column_index_offset, 0);
        EXPECT_EQ(old.meta.chunks[i].offset_index_offset, 0);
        EXPECT_EQ(old.meta.chunks[i].bloom_filter_offset, 0);
    }
}

// ============================================================================
// ColumnIndex/OffsetIndex parse vs analytic fixture ground truth
// ============================================================================

TEST(BoltParquetPageIndex, IdColumnPagesMatchRowIndexGroundTruth) {
    ParsedFile pf;
    parse_file("golden_pageindex.parquet", &pf);
    for (uint32_t g = 0; g < 2u; ++g) {
        ChunkIndex ix;
        read_chunk_index(pf, g, 0, &ix);   // col 0 = id (== global row idx)
        const int64_t rg_rows = pf.meta.row_groups[g].num_rows;
        const int64_t base = static_cast<int64_t>(g) * 1000;
        EXPECT_EQ(ix.ci.boundary_order, 1) << "id pages sorted ascending";
        EXPECT_EQ(ix.oi.pages[0].first_row_index, 0);
        for (uint32_t p = 0; p < ix.ci.n_pages; ++p) {
            ASSERT_EQ(ix.ci.pages[p].null_page, 0u);
            const int64_t first = ix.oi.pages[p].first_row_index;
            const int64_t next = (p + 1 < ix.oi.n_pages)
                                     ? ix.oi.pages[p + 1].first_row_index
                                     : rg_rows;
            // id == global row index ties ColumnIndex bounds to OffsetIndex
            // row locations exactly: min = base+first, max = base+next-1.
            EXPECT_EQ(page_stat_i64(ix.ci.pages[p], true), base + first);
            EXPECT_EQ(page_stat_i64(ix.ci.pages[p], false), base + next - 1);
            EXPECT_GT(ix.oi.pages[p].offset, 0);
            EXPECT_GT(ix.oi.pages[p].compressed_page_size, 0);
        }
        // Chunk-level stats == envelope of the page stats.
        const PqChunk& ch = chunk_at(pf, g, 0);
        int64_t clo = 0, chi = 0;
        const PqColumn& col = pf.meta.columns[0];
        ASSERT_TRUE(pq_stat_range_i64(col, ch, &clo, &chi));
        EXPECT_EQ(clo, page_stat_i64(ix.ci.pages[0], true));
        EXPECT_EQ(chi, page_stat_i64(ix.ci.pages[ix.ci.n_pages - 1], false));
    }
}

TEST(BoltParquetPageIndex, NullCountsOnMixedPages) {
    ParsedFile pf;
    parse_file("golden_pageindex.parquet", &pf);
    // col 3 = opt: rows with (row/100)%5 == 2 are null. pyarrow merges each
    // null span into a MIXED 200-row page (an all-null batch adds ~0
    // estimated bytes, so the size-based page split doesn't fire) — the
    // per-page null_counts must still sum to the exact ground truth.
    for (uint32_t g = 0; g < 2u; ++g) {
        ChunkIndex ix;
        read_chunk_index(pf, g, 3, &ix);
        ASSERT_EQ(ix.ci.has_null_counts, 1u);
        int64_t total_nulls = 0;
        for (uint32_t p = 0; p < ix.ci.n_pages; ++p) {
            const PqPageStat& ps = ix.ci.pages[p];
            ASSERT_GE(ps.null_count, 0);
            EXPECT_EQ(ps.null_page, 0u);   // mixed pages, never ALL null
            total_nulls += ps.null_count;
        }
        // Ground truth: rowgroup g covers global rows [g*1000,(g+1)*1000);
        // nulls where (row/100)%5==2 -> exactly 200 null rows per rowgroup.
        EXPECT_EQ(total_nulls, 200) << "rowgroup " << g;
    }
}

TEST(BoltParquetPageIndex, AllNullColumnYieldsNullPages) {
    ParsedFile pf;
    parse_file("golden_pageindex.parquet", &pf);
    // col 4 = allnull: 100% null -> EVERY page of the chunk is a null page
    // with empty bounds, and null_counts equal the page row counts.
    for (uint32_t g = 0; g < 2u; ++g) {
        const PqChunk& ch = chunk_at(pf, g, 4);
        std::vector<PqPageStat> stats(kPqMaxPagesPerChunk);
        std::vector<PqPageLocation> locs(kPqMaxPagesPerChunk);
        PqColumnIndex ci{};
        ci.pages = stats.data();
        ci.pages_cap = static_cast<uint32_t>(stats.size());
        PqOffsetIndex oi{};
        oi.pages = locs.data();
        oi.pages_cap = static_cast<uint32_t>(locs.size());
        ASSERT_TRUE(pq_read_column_index(pf.buf.data(), pf.buf.size(), ch,
                                         &ci));
        ASSERT_TRUE(pq_read_offset_index(pf.buf.data(), pf.buf.size(), ch,
                                         &oi));
        ASSERT_EQ(ci.n_pages, oi.n_pages);
        ASSERT_GE(ci.n_pages, 1u);
        const int64_t rg_rows = pf.meta.row_groups[g].num_rows;
        int64_t total_nulls = 0;
        for (uint32_t p = 0; p < ci.n_pages; ++p) {
            const PqPageStat& ps = ci.pages[p];
            const int64_t first = oi.pages[p].first_row_index;
            const int64_t next = (p + 1 < oi.n_pages)
                                     ? oi.pages[p + 1].first_row_index
                                     : rg_rows;
            EXPECT_EQ(ps.null_page, 1u) << "g " << g << " page " << p;
            EXPECT_EQ(ps.min_len, 0u);              // null page: empty bounds
            EXPECT_EQ(ps.max_len, 0u);
            if (ci.has_null_counts != 0) {
                EXPECT_EQ(ps.null_count, next - first);
                total_nulls += ps.null_count;
            }
            // A null page must never claim to exclude anything.
            EXPECT_FALSE(pq_page_excludes_range_i64(pf.meta.columns[4], ps,
                                                    INT64_MIN,
                                                    INT64_MAX - 1));
            EXPECT_FALSE(pq_page_utf8_excludes_eq(ps, nullptr, 0));
        }
        if (ci.has_null_counts != 0) EXPECT_EQ(total_nulls, rg_rows);
        // Range pruning over an all-null chunk keeps every page (the
        // conservative contract — nulls are the caller's gate).
        PqPageSet s{};
        pq_prune_pages_i64(pf.meta.columns[4], ci, 0, 100, &s);
        EXPECT_EQ(s.n_survivors, ci.n_pages);
    }
}

TEST(BoltParquetPageIndex, Utf8PageBoundsSortedAndUsable) {
    ParsedFile pf;
    parse_file("golden_pageindex.parquet", &pf);
    ChunkIndex ix;
    read_chunk_index(pf, 0, 2, &ix);       // col 2 = name = "k%06d" (sorted)
    EXPECT_EQ(ix.ci.boundary_order, 1);
    for (uint32_t p = 0; p < ix.ci.n_pages; ++p) {
        const PqPageStat& ps = ix.ci.pages[p];
        ASSERT_GT(ps.min_len, 0u);
        ASSERT_GT(ps.max_len, 0u);
        EXPECT_LE(pq_bytes_lex_cmp(ps.min_bytes, ps.min_len,
                                   ps.max_bytes, ps.max_len), 0);
        if (p > 0) {
            const PqPageStat& prev = ix.ci.pages[p - 1];
            EXPECT_GT(pq_bytes_lex_cmp(ps.min_bytes, ps.min_len,
                                       prev.max_bytes, prev.max_len), 0);
        }
    }
}

// ============================================================================
// Pruning helpers — property tests against the analytic fixture
// ============================================================================

// Every row whose id lies in [q_lo, q_hi] MUST fall inside a surviving row
// range (no false pruning), and the fixture's page layout means selective
// queries genuinely drop pages.
TEST(BoltParquetPageIndex, RangePruneNeverDropsMatchingRows) {
    ParsedFile pf;
    parse_file("golden_pageindex.parquet", &pf);
    const PqColumn& col = pf.meta.columns[0];
    for (uint32_t g = 0; g < 2u; ++g) {
        ChunkIndex ix;
        read_chunk_index(pf, g, 0, &ix);
        const int64_t rg_rows = pf.meta.row_groups[g].num_rows;
        const int64_t base = static_cast<int64_t>(g) * 1000;
        for (int64_t q_lo = base - 150; q_lo <= base + 1050; q_lo += 97) {
            const int64_t q_hi = q_lo + 130;
            PqPageSet s{};
            pq_prune_pages_i64(col, ix.ci, q_lo, q_hi, &s);
            PqRowRange ranges[kPqMaxPagesPerChunk / 2 + 1];
            const uint32_t n_ranges = pq_surviving_row_ranges(
                ix.oi, s, rg_rows, ranges,
                static_cast<uint32_t>(sizeof(ranges) / sizeof(ranges[0])));
            // Ground truth: id == base + rowgroup-relative row.
            for (int64_t row = 0; row < rg_rows; ++row) {
                const int64_t id = base + row;
                if (id < q_lo || id > q_hi) continue;
                bool covered = false;
                for (uint32_t r = 0; r < n_ranges; ++r) {
                    if (row >= ranges[r].first_row &&
                        row < ranges[r].first_row + ranges[r].row_count) {
                        covered = true;
                        break;
                    }
                }
                ASSERT_TRUE(covered) << "rg " << g << " q_lo " << q_lo
                                     << " row " << row;
            }
        }
        // A 131-wide query inside the rowgroup keeps at most 3 of the ~10
        // pages — the prune genuinely bites.
        PqPageSet s{};
        pq_prune_pages_i64(col, ix.ci, base + 250, base + 349, &s);
        EXPECT_LT(s.n_survivors, ix.ci.n_pages);
        EXPECT_GE(s.n_survivors, 1u);
        // Disjoint query: zero survivors, zero ranges.
        pq_prune_pages_i64(col, ix.ci, base + 5000, base + 6000, &s);
        EXPECT_EQ(s.n_survivors, 0u);
        PqRowRange r1[8];
        EXPECT_EQ(pq_surviving_row_ranges(ix.oi, s, rg_rows, r1, 8u), 0u);
        // Whole-domain query: everything survives, coalesced to ONE range.
        pq_prune_pages_i64(col, ix.ci, INT64_MIN, INT64_MAX, &s);
        EXPECT_EQ(s.n_survivors, ix.ci.n_pages);
        PqRowRange r2[kPqMaxPagesPerChunk / 2 + 1];
        ASSERT_EQ(pq_surviving_row_ranges(ix.oi, s, rg_rows, r2,
                                          kPqMaxPagesPerChunk / 2 + 1), 1u);
        EXPECT_EQ(r2[0].first_row, 0);
        EXPECT_EQ(r2[0].row_count, rg_rows);
    }
}

TEST(BoltParquetPageIndex, Utf8EqPruneFindsTheOnePage) {
    ParsedFile pf;
    parse_file("golden_pageindex.parquet", &pf);
    ChunkIndex ix;
    read_chunk_index(pf, 0, 2, &ix);       // name, rowgroup 0
    const int64_t rg_rows = pf.meta.row_groups[0].num_rows;
    // "k000550" is row 550 — it must land in a surviving range.
    const char* q = "k000550";
    PqPageSet s{};
    pq_prune_pages_utf8_eq(ix.ci, reinterpret_cast<const uint8_t*>(q),
                           7u, &s);
    ASSERT_GE(s.n_survivors, 1u);
    EXPECT_LT(s.n_survivors, ix.ci.n_pages);
    PqRowRange ranges[kPqMaxPagesPerChunk / 2 + 1];
    const uint32_t n_ranges = pq_surviving_row_ranges(
        ix.oi, s, rg_rows, ranges, kPqMaxPagesPerChunk / 2 + 1);
    bool covered = false;
    for (uint32_t r = 0; r < n_ranges; ++r) {
        if (550 >= ranges[r].first_row &&
            550 < ranges[r].first_row + ranges[r].row_count) covered = true;
    }
    EXPECT_TRUE(covered);
    // A value past every page bound prunes everything.
    const char* q2 = "zzz";
    pq_prune_pages_utf8_eq(ix.ci, reinterpret_cast<const uint8_t*>(q2),
                           3u, &s);
    EXPECT_EQ(s.n_survivors, 0u);
}

// ============================================================================
// Helper unit tests on synthetic PqPageStat values
// ============================================================================

TEST(BoltParquetPageIndex, PageStatHelpersConservative) {
    PqColumn col{};
    col.physical = PqType::Int32;
    PqPageStat ps{};
    ps.null_count = -1;
    // Absent stats: no range, no exclusion.
    int64_t lo = 0, hi = 0;
    EXPECT_FALSE(pq_page_range_i64(col, ps, &lo, &hi));
    EXPECT_FALSE(pq_page_excludes_range_i64(col, ps, 0, 10));
    // INT32 sign extension.
    const int32_t mn = -70000, mx = -5;
    std::memcpy(ps.min_bytes, &mn, 4); ps.min_len = 4;
    std::memcpy(ps.max_bytes, &mx, 4); ps.max_len = 4;
    ASSERT_TRUE(pq_page_range_i64(col, ps, &lo, &hi));
    EXPECT_EQ(lo, -70000);
    EXPECT_EQ(hi, -5);
    EXPECT_TRUE(pq_page_excludes_range_i64(col, ps, 0, 100));
    EXPECT_FALSE(pq_page_excludes_range_i64(col, ps, -6, 100));
    // Reversed pair => corrupt => never exclude.
    std::memcpy(ps.min_bytes, &mx, 4);
    std::memcpy(ps.max_bytes, &mn, 4);
    EXPECT_FALSE(pq_page_range_i64(col, ps, &lo, &hi));
    EXPECT_FALSE(pq_page_excludes_range_i64(col, ps, 0, 100));
    // Null page => never exclude, even with (stale) bounds present.
    std::memcpy(ps.min_bytes, &mn, 4);
    std::memcpy(ps.max_bytes, &mx, 4);
    ps.null_page = 1;
    EXPECT_FALSE(pq_page_range_i64(col, ps, &lo, &hi));
    EXPECT_FALSE(pq_page_excludes_range_i64(col, ps, 0, 100));
}

// ============================================================================
// Hostile input — the index slices, mirroring the footer fuzz pattern
// ============================================================================

TEST(BoltParquetPageIndex, CorruptIndexSlicesNeverCrash) {
    ParsedFile pf;
    parse_file("golden_pageindex.parquet", &pf);
    const PqChunk& ch = chunk_at(pf, 0, 0);
    std::vector<PqPageStat> stats(kPqMaxPagesPerChunk);
    std::vector<PqPageLocation> locs(kPqMaxPagesPerChunk);

    // Truncations of the declared index lengths.
    for (int32_t cut = 0; cut <= ch.column_index_length; ++cut) {
        PqColumnIndex ci{};
        ci.pages = stats.data();
        ci.pages_cap = static_cast<uint32_t>(stats.size());
        (void)pq_parse_column_index(
            pf.buf.data() + ch.column_index_offset,
            static_cast<uint32_t>(ch.column_index_length - cut), &ci);
    }
    for (int32_t cut = 0; cut <= ch.offset_index_length; ++cut) {
        PqOffsetIndex oi{};
        oi.pages = locs.data();
        oi.pages_cap = static_cast<uint32_t>(locs.size());
        (void)pq_parse_offset_index(
            pf.buf.data() + ch.offset_index_offset,
            static_cast<uint32_t>(ch.offset_index_length - cut), &oi);
    }
    // Byte flips across both slices.
    std::vector<uint8_t> mut(pf.buf);
    for (int32_t i = 0; i < ch.column_index_length; ++i) {
        mut[static_cast<size_t>(ch.column_index_offset + i)] ^= 0xFF;
        PqColumnIndex ci{};
        ci.pages = stats.data();
        ci.pages_cap = static_cast<uint32_t>(stats.size());
        (void)pq_parse_column_index(mut.data() + ch.column_index_offset,
                                    static_cast<uint32_t>(
                                        ch.column_index_length), &ci);
        mut[static_cast<size_t>(ch.column_index_offset + i)] ^= 0xFF;
    }
    for (int32_t i = 0; i < ch.offset_index_length; ++i) {
        mut[static_cast<size_t>(ch.offset_index_offset + i)] ^= 0xFF;
        PqOffsetIndex oi{};
        oi.pages = locs.data();
        oi.pages_cap = static_cast<uint32_t>(locs.size());
        (void)pq_parse_offset_index(mut.data() + ch.offset_index_offset,
                                    static_cast<uint32_t>(
                                        ch.offset_index_length), &oi);
        mut[static_cast<size_t>(ch.offset_index_offset + i)] ^= 0xFF;
    }
    // Bogus chunk locations against the whole file bound.
    PqChunk bogus = ch;
    bogus.column_index_offset = static_cast<int64_t>(pf.buf.size()) - 2;
    bogus.column_index_length = 100;   // escapes the file
    PqColumnIndex ci{};
    ci.pages = stats.data();
    ci.pages_cap = static_cast<uint32_t>(stats.size());
    EXPECT_FALSE(pq_read_column_index(pf.buf.data(), pf.buf.size(), bogus,
                                      &ci));
    bogus = ch;
    bogus.offset_index_offset = 0;     // absent
    PqOffsetIndex oi{};
    oi.pages = locs.data();
    oi.pages_cap = static_cast<uint32_t>(locs.size());
    EXPECT_FALSE(pq_read_offset_index(pf.buf.data(), pf.buf.size(), bogus,
                                      &oi));
    SUCCEED();
}

// ============================================================================
// XXH64 — authoritative vectors (python xxhash 3.8.1, seed as noted)
// ============================================================================

TEST(BoltParquetBloom, Xxh64KnownVectors) {
    EXPECT_EQ(pq_xxh64(nullptr, 0, 0), 0xEF46DB3751D8E999ull);
    const uint8_t a[] = {'a'};
    EXPECT_EQ(pq_xxh64(a, 1, 0), 0xD24EC4F1A98C6E5Bull);
    const char* abc = "abc";
    EXPECT_EQ(pq_xxh64(reinterpret_cast<const uint8_t*>(abc), 3, 0),
              0x44BC2CF5AD770999ull);
    // 62 bytes: exercises the 32-byte stripe loop + 8/4/1-byte tails.
    const char* s62 =
        "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
    EXPECT_EQ(pq_xxh64(reinterpret_cast<const uint8_t*>(s62), 62, 0),
              0x7639D419DE614EEDull);
    // Non-zero seed.
    EXPECT_EQ(pq_xxh64(reinterpret_cast<const uint8_t*>(abc), 3, 42),
              0x13C1D910702770E6ull);
    // Spec plain-encoding helper (int64 12345 LE).
    EXPECT_EQ(pq_bloom_hash_i64(12345), 0xF641F64AB4EBB803ull);
}

// ============================================================================
// Bloom filters vs two independent external writers
// ============================================================================

// No false negatives ever; false positives rare (fpp 0.01 requested).
void check_bloom_file(const char* name, bool has_val_col) {
    ParsedFile pf;
    parse_file(name, &pf);
    ASSERT_EQ(pf.meta.n_row_groups, 1u);
    const uint32_t n_cols = pf.meta.n_columns;
    ASSERT_GE(n_cols, 2u);

    // Column 0: id = 10000 + 3*i.
    {
        const PqChunk& ch = chunk_at(pf, 0, 0);
        ASSERT_GT(ch.bloom_filter_offset, 0) << name;
        PqBloomFilter bf{};
        ASSERT_TRUE(pq_read_bloom(pf.buf.data(), pf.buf.size(), ch, &bf))
            << name;
        ASSERT_GE(bf.n_bytes, 32u);
        for (int64_t i = 0; i < 1000; ++i) {   // every inserted value: hit
            ASSERT_TRUE(pq_bloom_may_contain(bf,
                                             pq_bloom_hash_i64(10000 + 3 * i)))
                << name << " id i=" << i;
        }
        uint32_t fp = 0;                        // absent values: mostly miss
        for (int64_t i = 0; i < 10000; ++i) {
            if (pq_bloom_may_contain(bf, pq_bloom_hash_i64(10000 + 3 * i + 1)))
                ++fp;
        }
        EXPECT_LT(fp, 500u) << name << " id false-positive rate too high";
    }
    // Column 1: name = "user%05d".
    {
        const PqChunk& ch = chunk_at(pf, 0, 1);
        ASSERT_GT(ch.bloom_filter_offset, 0) << name;
        PqBloomFilter bf{};
        ASSERT_TRUE(pq_read_bloom(pf.buf.data(), pf.buf.size(), ch, &bf));
        char key[16];
        for (int i = 0; i < 1000; ++i) {
            std::snprintf(key, sizeof(key), "user%05d", i);
            ASSERT_TRUE(pq_bloom_may_contain(
                bf, pq_bloom_hash_bytes(
                        reinterpret_cast<const uint8_t*>(key), 9u)))
                << name << " name i=" << i;
        }
        uint32_t fp = 0;
        for (int i = 0; i < 10000; ++i) {
            std::snprintf(key, sizeof(key), "ghost%05d", i);
            if (pq_bloom_may_contain(
                    bf, pq_bloom_hash_bytes(
                            reinterpret_cast<const uint8_t*>(key), 10u)))
                ++fp;
        }
        EXPECT_LT(fp, 500u) << name << " name false-positive rate too high";
    }
    // Column 2 (pyarrow fixture only): val int32 = 17*i + 5.
    if (has_val_col) {
        const PqChunk& ch = chunk_at(pf, 0, 2);
        ASSERT_GT(ch.bloom_filter_offset, 0) << name;
        PqBloomFilter bf{};
        ASSERT_TRUE(pq_read_bloom(pf.buf.data(), pf.buf.size(), ch, &bf));
        for (int32_t i = 0; i < 1000; ++i) {
            ASSERT_TRUE(pq_bloom_may_contain(
                bf, pq_bloom_hash_i32(17 * i + 5))) << name << " val i=" << i;
        }
        uint32_t fp = 0;
        for (int32_t i = 0; i < 10000; ++i) {
            if (pq_bloom_may_contain(bf, pq_bloom_hash_i32(17 * i + 6))) ++fp;
        }
        EXPECT_LT(fp, 500u) << name << " val false-positive rate too high";
    }
}

TEST(BoltParquetBloom, PyarrowBloomMembership) {
    check_bloom_file("golden_bloom.parquet", /*has_val_col=*/true);
}

TEST(BoltParquetBloom, DuckdbBloomMembership) {
    check_bloom_file("golden_bloom_duckdb.parquet", /*has_val_col=*/false);
}

TEST(BoltParquetBloom, AbsentBloomIsAbsent) {
    ParsedFile pf;
    parse_file("golden_flat.parquet", &pf);
    for (uint32_t i = 0; i < pf.meta.n_chunks; ++i) {
        EXPECT_EQ(pf.meta.chunks[i].bloom_filter_offset, 0);
        PqBloomFilter bf{};
        EXPECT_FALSE(pq_read_bloom(pf.buf.data(), pf.buf.size(),
                                   pf.meta.chunks[i], &bf));
    }
}

// ============================================================================
// Bloom header — synthetic buffers (reject shapes) + hostile fuzz
// ============================================================================

// Hand-encode a spec BloomFilterHeader: numBytes + BLOCK + XXHASH +
// UNCOMPRESSED. Returns header size.
size_t craft_bloom_header(uint8_t* out, int32_t num_bytes) {
    size_t n = 0;
    out[n++] = 0x15;                            // field 1, i32
    uint64_t z = (static_cast<uint64_t>(num_bytes) << 1) ^
                 static_cast<uint64_t>(num_bytes >> 31);
    do { uint8_t b = z & 0x7F; z >>= 7; if (z) b |= 0x80; out[n++] = b; }
    while (z);
    for (int u = 0; u < 3; ++u) {               // fields 2,3,4: union arm 1
        out[n++] = 0x1C;                        // delta 1, struct
        out[n++] = 0x1C;                        // union field 1, struct
        out[n++] = 0x00;                        // inner empty struct STOP
        out[n++] = 0x00;                        // union STOP
    }
    out[n++] = 0x00;                            // header struct STOP
    return n;
}

TEST(BoltParquetBloom, SyntheticHeaderAcceptAndReject) {
    uint8_t buf[64 + 64];
    std::memset(buf, 0xAB, sizeof(buf));
    const size_t hdr = craft_bloom_header(buf, 64);
    PqBloomFilter bf{};
    uint64_t consumed = 0;
    // Accept: header + 64-byte bitset present.
    ASSERT_TRUE(pq_parse_bloom(buf, hdr + 64, &bf, &consumed));
    EXPECT_EQ(consumed, hdr);
    EXPECT_EQ(bf.n_bytes, 64u);
    EXPECT_EQ(bf.bitset, buf + hdr);
    // All-0xAB bitset: every bit pattern probe returns true (all bits set
    // in probed positions is unlikely) — just exercise, no crash.
    (void)pq_bloom_may_contain(bf, 0x0123456789ABCDEFull);
    // Reject: bitset truncated.
    EXPECT_FALSE(pq_parse_bloom(buf, hdr + 63, &bf, &consumed));
    // Reject: numBytes not a multiple of 32.
    uint8_t bad[64 + 64];
    std::memset(bad, 0, sizeof(bad));
    size_t bh = craft_bloom_header(bad, 48);
    EXPECT_FALSE(pq_parse_bloom(bad, bh + 48, &bf, &consumed));
    // Reject: numBytes too small.
    bh = craft_bloom_header(bad, 0);
    EXPECT_FALSE(pq_parse_bloom(bad, bh + 64, &bf, &consumed));
    // Reject: numBytes negative.
    bh = craft_bloom_header(bad, -32);
    EXPECT_FALSE(pq_parse_bloom(bad, bh + 64, &bf, &consumed));
    // Reject: unsupported union arm (algorithm field 2 instead of 1).
    size_t n = craft_bloom_header(bad, 64);
    // Patch first union's inner field header (0x1C at offset hdr0+1 where
    // hdr0 = 1 + varint(64) = 3): make it field 2 (delta 2, struct = 0x2C).
    bad[3 + 1] = 0x2C;
    EXPECT_FALSE(pq_parse_bloom(bad, n + 64, &bf, &consumed));
}

TEST(BoltParquetBloom, CorruptBloomSlicesNeverCrash) {
    ParsedFile pf;
    parse_file("golden_bloom.parquet", &pf);
    const PqChunk& ch = chunk_at(pf, 0, 0);
    ASSERT_GT(ch.bloom_filter_offset, 0);
    ASSERT_GT(ch.bloom_filter_length, 0);
    const uint64_t off = static_cast<uint64_t>(ch.bloom_filter_offset);
    const uint32_t blen = static_cast<uint32_t>(ch.bloom_filter_length);
    PqBloomFilter bf{};
    uint64_t consumed = 0;
    // Truncations.
    for (uint32_t cut = 0; cut <= blen; cut += (blen > 256 ? 7 : 1)) {
        (void)pq_parse_bloom(pf.buf.data() + off, blen - cut, &bf, &consumed);
    }
    // Byte flips over the header region (first 64 bytes cover it).
    std::vector<uint8_t> mut(pf.buf);
    const uint32_t flip_span = (blen < 64u) ? blen : 64u;
    for (uint32_t i = 0; i < flip_span; ++i) {
        mut[off + i] ^= 0xFF;
        if (pq_parse_bloom(mut.data() + off, blen, &bf, &consumed)) {
            (void)pq_bloom_may_contain(bf, 0xDEADBEEFCAFEF00Dull);
        }
        mut[off + i] ^= 0xFF;
    }
    SUCCEED();
}

}  // namespace
