#!/usr/bin/env python3
"""Generate include/bolt/kernels/bolt_utf8_case_tables.h.

The oracle is DuckDB's upper()/lower() (simple, one-code-point-to-one-code-
point Unicode case mapping), the reference chukonu's SQL difftest compares
against. Dense tables cover U+0000..U+058F (Latin-1, Latin Extended-A/B, IPA,
Greek, Cyrillic, Armenian) and U+1E00..U+1FFF (Latin Extended Additional,
Greek Extended); a handful of letterlike symbols lower-case into those blocks.
kSpecialCasing lists the code points where Python's full mapping (the
XPath/SPARQL reference) disagrees with the simple one.

    python3 scripts/gen_utf8_case_tables.py > include/bolt/kernels/bolt_utf8_case_tables.h
"""
import sys

import duckdb

DENSE = [("A", 0x0000, 0x0590), ("B", 0x1E00, 0x2000)]
SPARSE_SRC = [0x2126, 0x212A, 0x212B]


def mapping(con, cps, fn):
    rows = con.execute(
        "SELECT cp, %s(chr(cp)) FROM unnest(?) t(cp) ORDER BY cp" % fn, [cps]).fetchall()
    out = {}
    for cp, s in rows:
        if 0xD800 <= cp <= 0xDFFF or len(s) != 1:
            out[cp] = cp
            continue
        t = ord(s)
        assert t <= 0xFFFF, (hex(cp), hex(t))
        out[cp] = t
    return out


def emit(name, vals):
    print("inline constexpr uint16_t %s[%d] = {" % (name, len(vals)))
    for i in range(0, len(vals), 12):
        print("    " + ", ".join("0x%04X" % v for v in vals[i:i + 12]) + ",")
    print("};")


def main():
    con = duckdb.connect()
    print("// GENERATED by scripts/gen_utf8_case_tables.py from DuckDB %s upper()/lower()."
          % duckdb.__version__)
    print("// Do not edit by hand.")
    print("#pragma once\n\n#include <cstdint>\n")
    print("namespace bolt {\nnamespace kernels {\nnamespace utf8 {\nnamespace case_tables {\n")
    for tag, lo, hi in DENSE:
        cps = [c for c in range(lo, hi) if not 0xD800 <= c <= 0xDFFF]
        up, low = mapping(con, cps, "upper"), mapping(con, cps, "lower")
        print("inline constexpr uint32_t k%sLo = 0x%04X;" % (tag, lo))
        print("inline constexpr uint32_t k%sHi = 0x%04X;" % (tag, hi))
        emit("kUpper%s" % tag, [up[c] for c in range(lo, hi)])
        emit("kLower%s" % tag, [low[c] for c in range(lo, hi)])
        print()
    special = set()
    for tag, lo, hi in DENSE:
        cps = [c for c in range(lo, hi) if not 0xD800 <= c <= 0xDFFF]
        up, low = mapping(con, cps, "upper"), mapping(con, cps, "lower")
        for c in cps:
            if chr(c).upper() != chr(up[c]) or chr(c).lower() != chr(low[c]):
                special.add(c)
    special.add(0x03A3)   # final sigma: full lowercase is context dependent
    special = sorted(special)
    print("// Code points whose full Unicode case mapping (SpecialCasing.txt, as")
    print("// Python str.upper()/lower() apply it) differs from the simple mapping")
    print("// above, plus U+03A3 (final sigma). Sorted.")
    emit("kSpecialCasing", special)
    print()
    low = mapping(con, SPARSE_SRC, "lower")
    up = mapping(con, SPARSE_SRC, "upper")
    assert all(up[c] == c for c in SPARSE_SRC)
    print("inline constexpr uint32_t kLowerSparse[%d][2] = {" % len(SPARSE_SRC))
    for c in SPARSE_SRC:
        print("    {0x%04X, 0x%04X}," % (c, low[c]))
    print("};\n")
    print("}  // namespace case_tables\n}  // namespace utf8\n}  // namespace kernels\n}  // namespace bolt")


if __name__ == "__main__":
    sys.exit(main())
