// bolt/kernels/fintech.h — aggregator: include all Tier-1/2 fintech kernels.
//
// Usage: #include "bolt/kernels/fintech.h"
// instead of per-kernel includes. All 67 fintech headers are listed below in
// alphabetical order so grep finds them easily.

#pragma once

#include "bolt/kernels/fintech/almgren_chriss.h"
#include "bolt/kernels/fintech/amihud.h"
#include "bolt/kernels/fintech/arrival_price_impact.h"
#include "bolt/kernels/fintech/atr.h"
#include "bolt/kernels/fintech/autocorr.h"
#include "bolt/kernels/fintech/bipower_var.h"
#include "bolt/kernels/fintech/bollinger_bands.h"
#include "bolt/kernels/fintech/cip_basis.h"
#include "bolt/kernels/fintech/circuit_breaker.h"
#include "bolt/kernels/fintech/column_primitives.h"
#include "bolt/kernels/fintech/cornish_fisher_var.h"
#include "bolt/kernels/fintech/corwin_schultz.h"
#include "bolt/kernels/fintech/cusum.h"
#include "bolt/kernels/fintech/donchian_channel.h"
#include "bolt/kernels/fintech/drawdown.h"
#include "bolt/kernels/fintech/effective_spread.h"
#include "bolt/kernels/fintech/ema.h"
#include "bolt/kernels/fintech/ewcov.h"
#include "bolt/kernels/fintech/ewma.h"
#include "bolt/kernels/fintech/fat_finger_guard.h"
#include "bolt/kernels/fintech/forward_points.h"
#include "bolt/kernels/fintech/funding_apr.h"
#include "bolt/kernels/fintech/funding_cost.h"
#include "bolt/kernels/fintech/garman_klass.h"
#include "bolt/kernels/fintech/historical_cvar.h"
#include "bolt/kernels/fintech/historical_var.h"
#include "bolt/kernels/fintech/implementation_shortfall.h"
#include "bolt/kernels/fintech/kalman1d.h"
#include "bolt/kernels/fintech/kalman_hedge_ratio.h"
#include "bolt/kernels/fintech/kyle_lambda.h"
#include "bolt/kernels/fintech/l1_imbalance.h"
#include "bolt/kernels/fintech/log_returns.h"
#include "bolt/kernels/fintech/macd.h"
#include "bolt/kernels/fintech/max_drawdown.h"
#include "bolt/kernels/fintech/med_rv.h"
#include "bolt/kernels/fintech/microprice.h"
#include "bolt/kernels/fintech/midprice.h"
#include "bolt/kernels/fintech/monotonic_deque.h"
#include "bolt/kernels/fintech/ofi.h"
#include "bolt/kernels/fintech/open_interest_delta.h"
#include "bolt/kernels/fintech/outlier_flag_mad.h"
#include "bolt/kernels/fintech/parkinson.h"
#include "bolt/kernels/fintech/perp_fair_price.h"
#include "bolt/kernels/fintech/price_band_guard.h"
#include "bolt/kernels/fintech/quoted_spread.h"
#include "bolt/kernels/fintech/realized_var.h"
#include "bolt/kernels/fintech/risk_metrics_vol.h"
#include "bolt/kernels/fintech/rogers_satchell.h"
#include "bolt/kernels/fintech/roll_spread.h"
#include "bolt/kernels/fintech/rolling_correlation.h"
#include "bolt/kernels/fintech/rolling_kurt.h"
#include "bolt/kernels/fintech/rolling_min_max.h"
#include "bolt/kernels/fintech/rolling_skew.h"
#include "bolt/kernels/fintech/rolling_std.h"
#include "bolt/kernels/fintech/rolling_zscore.h"
#include "bolt/kernels/fintech/rsi.h"
#include "bolt/kernels/fintech/sharpe_ratio.h"
#include "bolt/kernels/fintech/signed_volume.h"
#include "bolt/kernels/fintech/sma.h"
#include "bolt/kernels/fintech/sorted_ring.h"
#include "bolt/kernels/fintech/sortino_ratio.h"
#include "bolt/kernels/fintech/state.h"
#include "bolt/kernels/fintech/stochastic_osc.h"
#include "bolt/kernels/fintech/throttle_check.h"
#include "bolt/kernels/fintech/vwap_twap.h"
#include "bolt/kernels/fintech/welford_mean_var.h"
