# CompileShaderToHeader.cmake -- compiles a GLSL compute shader to SPIR-V
# via glslc and wraps the words as an embedded C++ header (no runtime
# filesystem access needed to load a shader -- see bolt_vulkan.h's BLLM-47
# banner). Invoked as a custom command at build time, once per shader.
#
# Required variables (passed via -D on the `cmake -P` invocation):
#   GLSLC     -- path to glslc
#   SRC       -- input .comp file
#   OUT       -- output .h file
#   VAR_NAME  -- C++ identifier for the generated uint32_t array

# --target-env=vulkan1.2: enables Vulkan 1.1+ features -- notably the
# GL_KHR_shader_subgroup_* ops (subgroupAdd) the matvec/rmsnorm reduction
# shaders use (BLLM-160/176). glslc defaults to vulkan1.0, which rejects them.
execute_process(
    COMMAND "${GLSLC}" -fshader-stage=compute --target-env=vulkan1.2 -mfmt=c "${SRC}" -o "${OUT}.tmp"
    RESULT_VARIABLE _glslc_result
    ERROR_VARIABLE _glslc_error
)
if(NOT _glslc_result EQUAL 0)
    message(FATAL_ERROR "glslc failed compiling ${SRC}:\n${_glslc_error}")
endif()

file(READ "${OUT}.tmp" _spirv_body)
file(REMOVE "${OUT}.tmp")

file(WRITE "${OUT}"
"#pragma once
// Auto-generated by CompileShaderToHeader.cmake from ${SRC} -- do not edit.
#include <cstddef>
#include <cstdint>

namespace bolt::vulkan::shaders {

inline constexpr uint32_t ${VAR_NAME}[] = ${_spirv_body};
inline constexpr size_t ${VAR_NAME}_size = sizeof(${VAR_NAME});

}  // namespace bolt::vulkan::shaders
")
